version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stormapp
    ports:
      - "5432:5432"
    